### ISSUE TITLE
Not-valid swagger

### ISSUE THREAD

**Issue by SergiiShapoval** [chargify/api-reference-export#2]
Hi, 
I am trying to import exported swagger to https://editor.swagger.io/ and it shows many errors in a document, Are there any plans to fix swagger errors?

**Comment by SergiiShapoval** [comment]
these issues don't allow to generate go client from Swagger definition:

> $ go run github.com/go-swagger/go-swagger/cmd/swagger validate https://raw.githubusercontent.com/chargify/api-reference-export/master/oas-swagger-stoplight.yaml
json: cannot unmarshal string into Go struct field SwaggerProps.paths of type []interface {}
exit status 1

same for other libraries
> $ java -jar swagger-codegen-cli.jar generate -i api/openapi/chargify.json -l go -o internal/common/client/chargify/ -v
....
12:21:25.412 [Thread-0] ERROR i.s.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('﻿' (code 65279 / 0xfeff)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (StringReader); line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:635)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1952)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:781)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4622)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3042)
        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:210)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
        at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:94)
        at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:44)
        at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:89)
        at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
        at io.swagger.codegen.v3.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:522)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:376)
        at java.base/java.lang.Thread.run(Thread.java:829)
12:21:25.420 [Thread-0] INFO  i.s.c.v.i.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
Exception in thread "Thread-0" java.lang.RuntimeException: missing OpenAPI input!
        at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:768)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:378)
        at java.base/java.lang.Thread.run(Thread.java:829)
